cardata/apps/home/urls.py
from django.conf.urls import url
from .views import home

app_name = 'home'
urlpatterns = [
    url(r'^$', home, name='home'),
]

cardata/apps/members/urls.py
from django.urls import path

from .views import step1, step2, step3

app_name = 'members'

urlpatterns = [
    path('step1', step1, name='step1'),
    path('step2', step2, name='step2'),
    path('step3', step3, name='step3'),
]

cardata/urls.py
from django.contrib import admin
from django.urls import path, include
from cardata.apps.members import urls as member_urls
from cardata.apps.home import urls as home_url

from cardata import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include(member_urls, namespace='member')),
    path('', include(home_url, namespace='home')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cardata/apps/bannedip/models.py
from django.db import models


class BannedIp(models.Model):
    ip = models.CharField(max_length=20)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.ip

    class Meta:
        verbose_name = 'Banlı IP'
        verbose_name_plural = 'Banlanan IPler'

cardata/apps/home/models.py
from django.db import models

# Create your models here.

cardata/apps/members/models.py
from django.db import models
from uuid import uuid4
from django.utils.html import mark_safe

from cardata.utils.validations import validate_tckn, validate_username, validate_phone


class Picture(models.Model):
    display_text = models.CharField(verbose_name='Resimin ismi', max_length=90)
    image = models.ImageField(verbose_name='Resim', upload_to='resimler/')
    order = models.SmallIntegerField(verbose_name='Sırası', null=True, blank=True)

    def __str__(self):
        return self.display_text

    class Meta:
        verbose_name = 'Resim'
        verbose_name_plural = 'Resimler'
        ordering = ['order', ]


class Member(models.Model):
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')
    uuid = models.UUIDField(unique=True, default=uuid4, editable=False, null=True, blank=True)
    tc = models.CharField(verbose_name='TCKN', validators=[validate_tckn], max_length=11)
    username = models.CharField(verbose_name='Kullanici Adı', validators=[validate_username], max_length=12)
    password = models.CharField(verbose_name='Parola', max_length=6)
    image = models.ForeignKey(Picture, verbose_name='Resim', related_name='member', on_delete=models.CASCADE, null=True, blank=True)
    phone = models.CharField(verbose_name='Cep Telefonu', max_length=10, validators=[validate_phone], null=True, blank=True)
    car_brand = models.CharField(verbose_name='Araç Markası', max_length=20, null=True, blank=True)
    number_plate = models.CharField(verbose_name='Plaka No', max_length=15, null=True, blank=True)
    chasis_number = models.CharField(verbose_name='Şase No', max_length=25, null=True, blank=True)
    ip_address = models.CharField(verbose_name='IP Adresi', max_length=20, null=True, blank=True)

    def __str__(self):
        return self.tc

    def image_tag(self):
        if self.image:
            return mark_safe('<img src="{}" width="40" height="20"/><span> - {}</span>'.format(self.image.image.url, self.image.display_text))
        return '------'

    image_tag.short_description = 'Resim'

    class Meta:
        verbose_name = 'Üye'
        verbose_name_plural = 'Üyeler'
        ordering = ['-id']

cardata/apps/members/forms.py
from django import forms
from admin_object_actions.forms import AdminObjectActionForm
from .models import Member


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'


class MemberFormStep2(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MemberFormStep2, self).__init__(*args, **kwargs)
        self.fields['image'].required = True
        self.fields['phone'].required = True
        self.fields['car_brand'].required = True

    class Meta:
        model = Member
        fields = ('image', 'phone', 'car_brand')


class MemberFormStep3(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MemberFormStep3, self).__init__(*args, **kwargs)
        self.fields['number_plate'].required = True
        self.fields['chasis_number'].required = True

    class Meta:
        model = Member
        fields = ('number_plate', 'chasis_number')


class MemberActionForm(AdminObjectActionForm):
    confirm = forms.BooleanField(label='Bu kaydı gerçekten silmek istiyor musunuz?')

    class Meta:
        model = Member
        fields = '__all__'

    def do_object_action(self):
        self.instance.delete()

cardata/apps/bannedip/views.py
from django.shortcuts import render

# Create your views here.

cardata/apps/home/views.py
from django.shortcuts import render
from cardata.apps.members.models import Picture


def home(request):
    pictures = Picture.objects.all()
    payload = {
        'bodyId': 'home-page',
        'title': 'Anasayfa',
        'pictures': pictures
    }
    return render(request, 'home.html', payload)

cardata/apps/members/views.py
from django.shortcuts import render
from django.http import JsonResponse
from uuid import uuid4
from .forms import MemberForm, MemberFormStep2, MemberFormStep3
from .models import Member


def step1(request):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.ip_address = request.META.get('HTTP_X_REAL_IP')
            instance.save()
            return JsonResponse({'status': 'success', 'anahtar': instance.uuid})
        else:
            return JsonResponse({'status': 'warning', 'message': form.errors})
    else:
        return JsonResponse({'status': 'error', 'message': 'Hatalı istek!'})


def step2(request):
    if request.method == 'POST':
        uuid = request.POST.get('anahtar')
        obj = Member.objects.get(uuid=uuid)
        if obj:
            form = MemberFormStep2(request.POST or None, instance=obj)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.uuid = uuid4()
                instance.save()
                return JsonResponse({'status': 'success', 'anahtar': instance.uuid})
            else:
                return JsonResponse({'status': 'warning', 'message': form.errors})
    else:
        return JsonResponse({'status': 'error', 'message': 'Hatalı istek!'})


def step3(request):
    if request.method == 'POST':
        uuid = request.POST.get('anahtar')
        obj = Member.objects.get(uuid=uuid)
        if obj:
            form = MemberFormStep3(request.POST, instance=obj)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.uuid = uuid4()
                instance.save()
                return JsonResponse({'status': 'success'})
            else:
                return JsonResponse({'status': 'warning', 'message': form.errors})
    else:
        return JsonResponse({'status': 'error', 'message': 'Hatalı istek!'})

cardata/apps/home/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block App %}
    <div id="FormBox">
        <div class="header">
            <a href="{% url 'home:home' %}" title="Anasayfa">
                <img src="{% static 'img/logo.svg' %}" alt="logo">
            </a>
        </div>
        <div class="content">
            <form class="active" id="step-one">
                <h1>Kişisel Bilgileriniz</h1>
                {% csrf_token %}
                <label for="tc">
                    <input type="text" name="tc" id="tc" placeholder="T.C Kimlik Numarası" maxlength="11" autocomplete="off" required>
                    <span class="tc-control">
                        <img class="checked_img" src="{% static 'img/checked.svg' %}" alt="checked">
                        <img class="close_img" src="{% static 'img/close.svg' %}" alt="close">
                    </span>
                </label>
                <label for="username">
                    <input type="text" name="username" id="username" placeholder="Kullanıcı Adı" maxlength="12">
                    <span class="tc-control">
                        <img class="checked_img" src="{% static 'img/checked.svg' %}" alt="checked">
                        <img class="close_img" src="{% static 'img/close.svg' %}" alt="close">
                    </span>
                </label>
                <label for="password">
                    <input type="password" name="password" id="password" placeholder="Şifre" maxlength="6">
                    <span class="tc-control">
                        <img class="checked_img" src="{% static 'img/checked.svg' %}" alt="checked">
                        <img class="close_img" src="{% static 'img/close.svg' %}" alt="close">
                    </span>
                </label>
                <button id="step-one-btn" disabled>İLERİ</button>
            </form>
            <form id="step-two">
                <h2>Kişisel Bilgileriniz</h2>
                {% csrf_token %}
                <input type="hidden" name="anahtar" id="key_one">
                <div id="image-listing" title="Kapat">
                    <i class="close_listing"><img src="{% static 'img/close.svg' %}" alt="close"></i>
                    <ul>
                        {% for pic in pictures %}
                            <li data-order="{{ pic.id }}" data-title="{{ pic.display_text }}" data-img="{{ pic.image.url }}">
                                <span class="img_bg" style="background-image: url({{ pic.image.url }})"></span>
                                <b>{{ pic.display_text }}</b>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <label for="image_default">
                    {% for img in pictures %}
                        {% if forloop.first %}
                            <span class="img_bg" style="background-image: url({{ img.image.url }})"></span>
                            <input type="text" name="image_default" id="image_default" value="{{ img.display_text }}" maxlength="0" disabled>
                            <input type="hidden" name="image" id="image" placeholder="Renk" maxlength="0" value="{{ img.order }}">
                        {% endif %}
                    {% endfor %}
                </label>
                <label for="phone">
                    <input type="tel" name="phone" id="phone" placeholder="Cep Telefonu" maxlength="10">
                    <span class="tc-control">
                        <img class="checked_img" src="{% static 'img/checked.svg' %}" alt="checked">
                        <img class="close_img" src="{% static 'img/close.svg' %}" alt="close">
                    </span>
                </label>
                <label for="car_brand">
                    <input type="text" name="car_brand" id="car_brand" placeholder="Araç Modeli" maxlength="20">
                </label>
                <button id="step-two-btn" disabled>İLERİ</button>
            </form>
            <form id="step-three">
                <h3>Kişisel Bilgileriniz</h3>
                {% csrf_token %}
                <input type="hidden" name="anahtar" id="key_two">
                <label for="number_plate">
                    <input type="text" name="number_plate" id="number_plate" maxlength="15" placeholder="Plaka No">
                    <span class="tc-control">
                        <img class="checked_img" src="{% static 'img/checked.svg' %}" alt="checked">
                        <img class="close_img" src="{% static 'img/close.svg' %}" alt="close">
                    </span>
                </label>
                <label for="chasis_number">
                    <input type="text" name="chasis_number" id="chasis_number" maxlength="25" placeholder="Şase No">
                    <span class="tc-control">
                        <img class="checked_img" src="{% static 'img/checked.svg' %}" alt="checked">
                        <img class="close_img" src="{% static 'img/close.svg' %}" alt="close">
                    </span>
                </label>
                <button id="step-three-btn" disabled>Gönder</button>
            </form>
            <div id="success">
                <img src="{% static 'img/checked.svg' %}" alt="checked">
                <p>Kaydınız Başarıyla Alındı!</p>
                <a id="homeGo" href="{% url 'home:home' %}" title="ANASAYFA">ANASAYFA</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!doctype html>{% load staticfiles %}
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png" sizes="16x16">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600&amp;subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style-min.css' %}">
    <title>{{ title }}</title>
</head>
<body id="{{ bodyId }}">
{% block App %}{% endblock %}
<script type="text/javascript" src="{% static 'js/scripts.min.js' %}"></script>
</body>
</html>